version: '3'
services:
  mysql-master-1:
    image: mysql:8.0
    container_name: mysql-master-1
    restart: unless-stopped
    env_file: .env
    cap_add:
      - all
    volumes:
      - ./master-1/my.cnf:/etc/my.cnf
    environment:
      - TZ:${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - "mysql"
  
  mysql-master-2:
    image: mysql:8.0
    container_name: mysql-master-2
    restart: unless-stopped
    env_file: .env
    cap_add:
      - all
    volumes:
      - ./master-2/my.cnf:/etc/my.cnf
    environment:
      - TZ:${TZ}
      - MYSQL_USER:${MYSQL_USER}
      - MYSQL_PASSWORD:${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD:${MYSQL_ROOT_PASSWORD}
    networks:
      default:
        aliases:
          - "mysql"